# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_202201211_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
